# Generated by Django 4.2.7 on 2023-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="url",
            field=models.URLField(
                default="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fdefault-image&psig=AOvVaw1Kvv7J5_E-uzKGQxKkdMnw&ust=1701874811903000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCOjM_-7H-IIDFQAAAAAdAAAAABAE"
            ),
        ),
    ]
