# Generated by Django 4.2.7 on 2023-12-07 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_listing_highest_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlists",
            field=models.ManyToManyField(
                blank=True, related_name="watchlists", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
