# Generated by Django 4.2.7 on 2023-12-07 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0009_listing_watchlists"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="watchlists",
        ),
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
