# Generated by Django 4.2.7 on 2023-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Fun", "Fun"),
                    ("Inside", "Inside"),
                    ("Outside", "Outside"),
                    ("Computer", "Computer"),
                ],
                max_length=10,
            ),
        ),
    ]
